import React, { useEffect, useState, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import DashboardLayout from '@/components/DashboardLayout';
import { api } from '@/services/api';
import { Calendar as BigCalendar, momentLocalizer } from 'react-big-calendar';
import moment from 'moment';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { Textarea } from '@/components/ui/textarea';
import { toast } from 'sonner';
import { Plus, Trash2, ClipboardCheck, Edit } from 'lucide-react';
import 'react-big-calendar/lib/css/react-big-calendar.css';

const localizer = momentLocalizer(moment);

const CalendarPage = () => {
  const navigate = useNavigate();
  const [events, setEvents] = useState([]);
  const [students, setStudents] = useState([]);
  const [teachers, setTeachers] = useState([]);
  const [classes, setClasses] = useState([]);
  const [studentGroups, setStudentGroups] = useState([]);
  const [loading, setLoading] = useState(true);
  const [open, setOpen] = useState(false);
  const [viewOpen, setViewOpen] = useState(false);
  const [selectedEvent, setSelectedEvent] = useState(null);
  const [isEditing, setIsEditing] = useState(false);
  const [editingEventId, setEditingEventId] = useState(null);
  const [calendarDate, setCalendarDate] = useState(new Date());
  const [calendarView, setCalendarView] = useState('month');
  const [formData, setFormData] = useState({
    title: '',
    description: '',
    start_date: new Date().toISOString().slice(0, 16),
    end_date: new Date(Date.now() + 60 * 60 * 1000).toISOString().slice(0, 16),
    event_type: 'class',
    class_id: '',
    participants: []
  });

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    try {
      const [eventsRes, studentsRes, teachersRes, classesRes, groupsRes] = await Promise.all([
        api.getEvents(),
        api.getStudents(),
        api.getTeachers(),
        api.getClasses(),
        api.getStudentGroups()
      ]);
      setEvents(eventsRes.data);
      setStudents(studentsRes.data);
      setTeachers(teachersRes.data);
      setClasses(classesRes.data);
      setStudentGroups(groupsRes.data);
    } catch (error) {
      toast.error('Failed to fetch data');
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const data = {
        ...formData,
        start_date: new Date(formData.start_date).toISOString(),
        end_date: new Date(formData.end_date).toISOString()
      };
      
      if (isEditing && editingEventId) {
        await api.updateEvent(editingEventId, data);
        toast.success('Event updated successfully');
      } else {
        await api.createEvent(data);
        toast.success('Event created successfully');
      }
      setOpen(false);
      resetForm();
      fetchData();
    } catch (error) {
      toast.error(error.response?.data?.detail || `Failed to ${isEditing ? 'update' : 'create'} event`);
    }
  };

  const resetForm = () => {
    setFormData({
      title: '',
      description: '',
      start_date: new Date().toISOString().slice(0, 16),
      end_date: new Date(Date.now() + 60 * 60 * 1000).toISOString().slice(0, 16),
      event_type: 'class',
      class_id: '',
      participants: []
    });
    setIsEditing(false);
    setEditingEventId(null);
  };

  // Handle class selection to prefill event name
  const handleClassChange = useCallback((classId) => {
    setFormData(prev => {
      const newData = { ...prev, class_id: classId === "none" ? "" : classId };
      
      // Prefill title with class name if a class is selected and title is empty or was auto-generated
      if (classId && classId !== "none") {
        const selectedClass = classes.find(c => c.id === classId);
        if (selectedClass) {
          // Only prefill if title is empty or matches previous class name pattern
          const isEmptyOrAutoGenerated = !prev.title || 
            classes.some(c => prev.title === `${c.name} - ${c.subject}` || prev.title === c.name);
          
          if (isEmptyOrAutoGenerated) {
            newData.title = `${selectedClass.name} - ${selectedClass.subject}`;
          }
        }
      }
      
      return newData;
    });
  }, [classes]);

  const calendarEvents = events.map(event => ({
    id: event.id,
    title: event.title,
    start: new Date(event.start_date),
    end: new Date(event.end_date),
    resource: event
  }));

  const handleEventClick = (event) => {
    setSelectedEvent(event.resource);
    setViewOpen(true);
  };

  const handleDeleteEvent = async () => {
    if (!selectedEvent) return;
    if (window.confirm('Are you sure you want to delete this event?')) {
      try {
        await api.deleteEvent(selectedEvent.id);
        toast.success('Event deleted successfully');
        setViewOpen(false);
        setSelectedEvent(null);
        fetchData();
      } catch (error) {
        toast.error('Failed to delete event');
      }
    }
  };

  const handleEditEvent = () => {
    if (!selectedEvent) return;
    
    // Parse the dates properly
    const startDate = new Date(selectedEvent.start_date);
    const endDate = new Date(selectedEvent.end_date);
    
    setFormData({
      title: selectedEvent.title || '',
      description: selectedEvent.description || '',
      start_date: startDate.toISOString().slice(0, 16),
      end_date: endDate.toISOString().slice(0, 16),
      event_type: selectedEvent.event_type || 'class',
      class_id: selectedEvent.class_id || '',
      participants: selectedEvent.participants || []
    });
    setIsEditing(true);
    setEditingEventId(selectedEvent.id);
    setViewOpen(false);
    setOpen(true);
  };

  const handleSlotSelect = useCallback((slotInfo) => {
    // When clicking on a date slot, open the add event dialog with that date pre-filled
    const startDate = new Date(slotInfo.start);
    const endDate = new Date(slotInfo.start);
    endDate.setHours(endDate.getHours() + 1);
    
    setFormData({
      title: '',
      description: '',
      start_date: startDate.toISOString().slice(0, 16),
      end_date: endDate.toISOString().slice(0, 16),
      event_type: 'class',
      class_id: '',
      participants: []
    });
    setIsEditing(false);
    setEditingEventId(null);
    setOpen(true);
  }, []);

  const handleAddEventClick = () => {
    resetForm();
    setOpen(true);
  };

  const getEventTypeColor = (type) => {
    switch (type) {
      case 'exam': return 'bg-red-100 text-red-800';
      case 'holiday': return 'bg-green-100 text-green-800';
      case 'meeting': return 'bg-orange-100 text-orange-800';
      case 'class': return 'bg-blue-100 text-blue-800';
      default: return 'bg-slate-100 text-slate-800';
    }
  };

  const allParticipants = [...students, ...teachers];

  return (
    <DashboardLayout>
      <div data-testid="calendar-page">
        <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4 mb-6 sm:mb-8">
          <div>
            <h1 className="text-3xl sm:text-4xl font-bold text-slate-900 tracking-tight font-heading">Calendar</h1>
            <p className="text-sm sm:text-base leading-relaxed text-slate-600 mt-2">Manage classes, exams, holidays and events</p>
          </div>
          <Button
            data-testid="add-event-button"
            onClick={handleAddEventClick}
            className="bg-primary hover:bg-primary-hover w-full sm:w-auto"
          >
            <Plus size={18} className="mr-2" />
            Add Event
          </Button>
          <Dialog open={open} onOpenChange={(isOpen) => { setOpen(isOpen); if (!isOpen) resetForm(); }}>
            <DialogContent className="max-w-md max-h-[90vh] overflow-y-auto">
              <DialogHeader>
                <DialogTitle>{isEditing ? 'Edit Event' : 'Create New Event'}</DialogTitle>
              </DialogHeader>
              <form onSubmit={handleSubmit} className="space-y-4 mt-4">
                <div>
                  <Label htmlFor="title">Title</Label>
                  <Input
                    id="title"
                    data-testid="event-title-input"
                    value={formData.title}
                    onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                    required
                    className="mt-1"
                  />
                </div>
                <div>
                  <Label htmlFor="description">Description (Optional)</Label>
                  <Textarea
                    id="description"
                    data-testid="event-description-input"
                    value={formData.description}
                    onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                    className="mt-1"
                    rows={3}
                    placeholder="Add event details..."
                  />
                </div>
                <div>
                  <Label htmlFor="event_type">Event Type</Label>
                  <Select
                    value={formData.event_type}
                    onValueChange={(value) => setFormData({ ...formData, event_type: value })}
                  >
                    <SelectTrigger className="mt-1" data-testid="event-type-select">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="class">Class</SelectItem>
                      <SelectItem value="exam">Exam</SelectItem>
                      <SelectItem value="holiday">Holiday</SelectItem>
                      <SelectItem value="meeting">Meeting</SelectItem>
                      <SelectItem value="other">Other</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label htmlFor="class_id">Related Class/Course (Optional)</Label>
                  <Select
                    value={formData.class_id || "none"}
                    onValueChange={handleClassChange}
                  >
                    <SelectTrigger className="mt-1" data-testid="event-class-select">
                      <SelectValue placeholder="Select class" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="none">None</SelectItem>
                      {classes.map(cls => (
                        <SelectItem key={cls.id} value={cls.id}>
                          {cls.name} - {cls.subject}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label htmlFor="start_date">Start Date & Time</Label>
                  <Input
                    id="start_date"
                    type="datetime-local"
                    data-testid="event-start-date-input"
                    value={formData.start_date}
                    onChange={(e) => setFormData({ ...formData, start_date: e.target.value })}
                    required
                    className="mt-1"
                  />
                </div>
                <div>
                  <Label htmlFor="end_date">End Date & Time</Label>
                  <Input
                    id="end_date"
                    type="datetime-local"
                    data-testid="event-end-date-input"
                    value={formData.end_date}
                    onChange={(e) => setFormData({ ...formData, end_date: e.target.value })}
                    required
                    className="mt-1"
                  />
                </div>
                <div>
                  <Label>Add by Student Groups</Label>
                  <Select
                    value=""
                    onValueChange={(groupId) => {
                      if (groupId && groupId !== "placeholder") {
                        const group = studentGroups.find(g => g.id === groupId);
                        if (group) {
                          const newParticipants = [...new Set([...formData.participants, ...group.student_ids])];
                          setFormData({ ...formData, participants: newParticipants });
                          toast.success(`Added ${group.name} to event`);
                        }
                      }
                    }}
                  >
                    <SelectTrigger className="mt-1" data-testid="event-group-select">
                      <SelectValue placeholder="Quick add group" />
                    </SelectTrigger>
                    <SelectContent>
                      {studentGroups.length === 0 ? (
                        <SelectItem value="placeholder" disabled>No groups available</SelectItem>
                      ) : (
                        studentGroups.map(group => (
                          <SelectItem key={group.id} value={group.id}>
                            {group.name} ({group.student_ids.length} students)
                          </SelectItem>
                        ))
                      )}
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label>Participants (Hold Ctrl/Cmd for multiple)</Label>
                  <select
                    multiple
                    data-testid="event-participants-select"
                    value={formData.participants}
                    onChange={(e) => {
                      const selected = Array.from(e.target.selectedOptions, option => option.value);
                      setFormData({ ...formData, participants: selected });
                    }}
                    className="w-full mt-1 px-3 py-2 border rounded-md border-slate-200 bg-slate-50 focus:bg-white focus:ring-2 focus:ring-blue-900/10 transition-colors"
                    style={{ minHeight: '100px' }}
                  >
                    <optgroup label="Students">
                      {students.map(student => (
                        <option key={student.id} value={student.id}>
                          {student.name}
                        </option>
                      ))}
                    </optgroup>
                    <optgroup label="Teachers">
                      {teachers.map(teacher => (
                        <option key={teacher.id} value={teacher.id}>
                          {teacher.name}
                        </option>
                      ))}
                    </optgroup>
                  </select>
                </div>
                <Button type="submit" data-testid="event-submit-button" className="w-full bg-primary hover:bg-primary-hover">
                  {isEditing ? 'Update Event' : 'Create Event'}
                </Button>
              </form>
            </DialogContent>
          </Dialog>
        </div>

        <div className="bg-white border border-slate-200 rounded-lg shadow-sm p-2 sm:p-6" style={{ height: '500px', minHeight: '500px' }}>
          {loading ? (
            <div className="flex items-center justify-center h-full">
              <div className="text-slate-500">Loading calendar...</div>
            </div>
          ) : (
            <BigCalendar
              localizer={localizer}
              events={calendarEvents}
              startAccessor="start"
              endAccessor="end"
              style={{ height: '100%' }}
              views={['month', 'week', 'day', 'agenda']}
              date={calendarDate}
              view={calendarView}
              onNavigate={(newDate) => setCalendarDate(newDate)}
              onView={(newView) => setCalendarView(newView)}
              onSelectEvent={handleEventClick}
              selectable={true}
              onSelectSlot={handleSlotSelect}
              eventPropGetter={(event) => {
                const eventType = event.resource.event_type;
                let backgroundColor = '#1E3A8A';
                if (eventType === 'exam') backgroundColor = '#EF4444';
                if (eventType === 'holiday') backgroundColor = '#10B981';
                if (eventType === 'meeting') backgroundColor = '#F97316';
                return { style: { backgroundColor, cursor: 'pointer' } };
              }}
            />
          )}
        </div>

        {/* Event View Dialog */}
        <Dialog open={viewOpen} onOpenChange={setViewOpen}>
          <DialogContent className="max-w-md">
            <DialogHeader>
              <DialogTitle className="flex items-center justify-between">
                <span>{selectedEvent?.title}</span>
                {selectedEvent && (
                  <span className={`px-2 py-1 rounded text-xs font-medium ${getEventTypeColor(selectedEvent.event_type)}`}>
                    {selectedEvent.event_type}
                  </span>
                )}
              </DialogTitle>
            </DialogHeader>
            {selectedEvent && (
              <div className="space-y-4 mt-4">
                {selectedEvent.description && (
                  <div>
                    <Label className="text-slate-500">Description</Label>
                    <p className="mt-1">{selectedEvent.description}</p>
                  </div>
                )}
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label className="text-slate-500">Start</Label>
                    <p className="mt-1 text-sm">
                      {new Date(selectedEvent.start_date).toLocaleDateString()}<br />
                      {new Date(selectedEvent.start_date).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </p>
                  </div>
                  <div>
                    <Label className="text-slate-500">End</Label>
                    <p className="mt-1 text-sm">
                      {new Date(selectedEvent.end_date).toLocaleDateString()}<br />
                      {new Date(selectedEvent.end_date).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </p>
                  </div>
                </div>
                {selectedEvent.class_id && (
                  <div>
                    <Label className="text-slate-500">Related Class</Label>
                    <p className="mt-1">
                      {classes.find(c => c.id === selectedEvent.class_id)?.name || 'Unknown'}
                    </p>
                  </div>
                )}
                {(() => {
                  // Show union of class students + explicit event participants — so the
                  // list always reflects current class enrolment, not a stale snapshot.
                  const ids = new Set(selectedEvent.participants || []);
                  if (selectedEvent.class_id) {
                    const cls = classes.find(c => c.id === selectedEvent.class_id);
                    (cls?.student_ids || []).forEach(id => ids.add(id));
                    (cls?.teacher_ids || []).forEach(id => ids.add(id));
                  }
                  if (ids.size === 0) return null;
                  return (
                    <div>
                      <Label className="text-slate-500">Participants</Label>
                      <div className="mt-1 flex flex-wrap gap-1" data-testid="event-participants-list">
                        {[...ids].map(pId => {
                          const participant = allParticipants.find(p => p.id === pId);
                          return participant ? (
                            <span key={pId} className="px-2 py-1 bg-slate-100 rounded text-xs">
                              {participant.name}
                            </span>
                          ) : null;
                        })}
                      </div>
                    </div>
                  );
                })()}
                
                {/* Mark Attendance Button */}
                <div className="pt-4 border-t border-slate-100">
                  <Button 
                    className="w-full"
                    onClick={() => {
                      setViewOpen(false);
                      navigate(`/attendance?event_id=${selectedEvent.id}&date=${selectedEvent.start_date?.split('T')[0]}`);
                    }}
                  >
                    <ClipboardCheck size={18} className="mr-2" />
                    Mark Attendance for this Event
                  </Button>
                </div>
              </div>
            )}
            <DialogFooter className="mt-6">
              <Button variant="outline" onClick={() => setViewOpen(false)}>
                Close
              </Button>
              <Button variant="outline" onClick={handleEditEvent} data-testid="edit-event-button">
                <Edit size={16} className="mr-2" />
                Edit
              </Button>
              <Button variant="destructive" onClick={handleDeleteEvent}>
                <Trash2 size={16} className="mr-2" />
                Delete
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>
    </DashboardLayout>
  );
};

export default CalendarPage;